apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zcid.fullname" . }}-secrets
  labels:
    {{- include "zcid.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  minio-access-key: {{ .Values.secrets.minioAccessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  encryption-key: {{ .Values.config.encryptionKey | quote }}
  {{- if .Values.secrets.argocdToken }}
  argocd-token: {{ .Values.secrets.argocdToken | quote }}
  {{- end }}
