apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: zcid-managed
  namespace: argocd
spec:
  description: "Projects managed by zcid platform"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
